### PR TITLE
Axios Instance Implementation with Token Refresh

### LINKED ISSUE #3: Implement Axios Instance
Create an Axios instance that:
- Automatically refreshes tokens on 401 errors
- Retries failed requests (once)
- If still an error, redirects to login

### PR DESCRIPTION
**Pull request by nikama-s**
## Description
Implemented a robust axios instance with automatic token refresh functionality and comprehensive error handling.

## Key Features
- **Automatic Token Refresh**: Handles 401 errors by automatically refreshing the access token, retries only once to prevent loops
- **Request Queuing**: Queues multiple requests during token refresh to prevent race conditions
- **Auth Endpoint Protection**: Special handling for auth endpoints to prevent refresh loops
- **Default Configuration**: Pre-configured with optimal settings for API communication

## Implementation Details
- Created axios instance with default configuration:
  - Content-Type: application/json
  - Timeout: 60 seconds
  - withCredentials: true (for cookie-based auth)
- Implemented response interceptor for:
  - Automatic token refresh on 401 errors
  - Request queuing during refresh
  - Error logging and handling
- Added token refresh mechanism with:
  - Refresh token endpoint integration
  - Request retry after successful refresh
  - Error handling for refresh failures

## Testing
Added comprehensive test suite covering:
- Default configuration validation
- Response interceptor behavior
- Token refresh logic
- Error handling scenarios
- Request queuing functionality

## Usage Example
```typescript
import api from '@/lib/api/axiosInstance';

// The instance is ready to use with automatic token refresh
const response = await api.get('some endpoint');
```
Closes #3

### CODE REVIEW

File: src/lib/api/axiosInstance.ts [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+            } else {
+              reject(
+                new Error(
+                  "Original request config is missing after token refresh."
+                )
+              );
+            }
+          });
+        });
+      }
```
Comment (yur-ochka) [inline src/lib/api/axiosInstance.ts:41]: Extract 401 handling logic into a dedicated handle401Error function to improve code readability and maintainability

**Review by yur-ochka — CHANGES_REQUESTED** [review]
Overall - a very solid work, good job!

**Review by yur-ochka — APPROVED** [review]
Nicely done!
